services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password123
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"

  app: &web_scraping_app
    container_name: web_scraping_app
    stdin_open: true
    platform: linux/x86_64
    tty: true
    build: .
    command: bash entrypoint.sh
    volumes:
      - .:/app
      - bundle_cache:/usr/local/bundle
      - /dev/shm:/dev/shm
    ports:
      - "3000:3000"
    depends_on:
      - db

  sidekiq:
    <<: *web_scraping_app
    container_name: sidekiq
    command: bundle exec sidekiq -C config/sidekiq.yml
    ports:
      - "3001:3000"

  redis:
    image: redis:7.0
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

volumes:
  db_data:
  bundle_cache:
  redis_data:
  rabbitmq_data:
