services:
  app: &web_scraping_service
    container_name: web_scraping_service
    stdin_open: true
    platform: linux/x86_64
    tty: true
    build: .
    command: sh /app/entrypoint.sh
    volumes:
      - .:/app
      - bundle_cache:/usr/local/bundle
      - /dev/shm:/dev/shm
    ports:
      - "${PORT:-3400}:3000"
    networks:
      - app-network
    env_file:
      - .env

  sidekiq:
    <<: *web_scraping_service
    container_name: sidekiq
    command: bundle exec sidekiq -C config/sidekiq.yml
    ports:
      - "${PORT:-3401}:3000"

networks:
  app-network:
    name: app-network
    external: true

volumes:
  bundle_cache:
