# frozen_string_literal: true

default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: <%= ENV.fetch('DB_USER') { 'root' } %>
  password: <%= ENV.fetch('DB_PASSWORD') { 'password123' } %>
  host: <%= ENV.fetch('DB_HOST') { 'db' } %>
  port: <%= ENV.fetch('DB_PORT') { 3306 } %>

development:
  <<: *default
  database: web_scraping_service_development

test:
  <<: *default
  database: web_scraping_service_test

production:
  <<: *default
  database: task_management_production
  username: <%= ENV['WEB_SCRAPING_SERVICE_DATABASE_USER'] %>
  password: <%= ENV['WEB_SCRAPING_SERVICE_DATABASE_PASSWORD'] %>
